title: Mislav Vuletić
email: mislav.vuletic@gmail.com
description: >- # this ignores values until a new key in yaml
  The home of Mislav Vuletić (MasterMedo), a Software Engineer who likes
  building things. A showcase of the publicly discloseable work I've done over
  the years.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://mastermedo.github.io
github_username: MasterMedo
linkedin_username: MasterMedo
author: Mislav Vuletić
show_excerpts: true
permalink: /:categories/:title
google_analytics: "G-30BEMRXG28"
google_tag_manager: "GTM-556MWK9"

header_pages:
  - about
  - resume
  - projects
  - stories

defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
