title: Mislav Vuletić
email: mislav@duck.com
description: >- # this ignores values until a new key in yaml
  This section is called a footer (surprise, surprise).
baseurl: "" # the subpath of your site, e.g. /blog
url: https://mislav.dev
github_username: MasterMedo
linkedin_username: MasterMedo
author: Mislav Vuletić
show_excerpts: true
permalink: /:categories/:title
google_analytics: "G-30BEMRXG28"
google_tag_manager: "GTM-556MWK9"
hotjar: true

header_pages:
  - about
  - resume
  - projects
  - stories

defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
